### ISSUE TITLE
Bug: Uncaught TypeError array_key_exists()

### ISSUE THREAD

**Issue by mark-todd** [rutek/dataclass#4]
Small bug - when the following object is specified, if an object other than expected is given:

Defined Classes:

```php
class InnerClass {
    public string $test;
}

class OuterClass {
    public InnerClass $inner;
}
```

Supplied JSON to transform (with a json_encode)

```json
{
    "inner": "wrongtype"
}
```

```
Uncaught TypeError: array_key_exists() expects parameter 2 to be array, int given in vendor/rutek/dataclass/src/Transform.php:69
Stack trace:
#0 vendor/rutek/dataclass/src/Transform.php(69): array_key_exists()
#1 vendor/rutek/dataclass/src/Transform.php(180): Rutek\Dataclass\Transform->to()
#2 vendor/rutek/dataclass/src/Transform.php(87): Rutek\Dataclass\Transform->checkType()
#3 vendor/rutek/dataclass/src/helpers.php(19): Rutek\Dataclass\Transform->to()
#4 Place in my code transform is used: Rutek\Dataclass\transform()
```

**Comment by rutek** [comment]
Thanks @mark-todd for placing this issue. It has been fixed in v0.1.0 which has been released just now.
